= Spring Cloud Gateway Demo
:toc:

== Rationale

This project aims to show the problems we faced with spring-cloud-gateway and related dependencies since upgrading to spring-boot-version 3.x

== Getting started

=== Build

[source,bash]
----
mvn clean install
----

=== Running the application locally

To locally run the application, use the following command:

[source,bash]
----
mvn spring-boot:run
----

The application starts on port 7000, the actuator endpoints are available under port 7010.

For local tests, a mockserver (simulating a backend-service) and keycloak can be started with the provided docker-compose file.

[source,bash]
----
docker-compose -f ./tooling/docker-compose.yaml up
----

The mockserver can be reached via http://localhost:7030 and exposes a dashboard to monitor all requests is available via http://localhost:7030/mockserver/dashboard[Mockserver Dashboard].

The keycloak can be reached via http://localhost:7020.
The following users are available within the keycloak:

|===
|Username | Password

|admin
|admin

|testuser
|test1234
|===

Some example requests are available link:./tooling/requests.http[here].