= Spring Cloud Gateway Demo
:toc:

== Rationale

This project aims to show the problems we are facing with logging and tracing when upgrading to spring boot 3 in a reactive environment using netty.

== Getting started

=== Build

The 'main' branch contains the functioning spring-boot-2 version including tests that show our expectations.

[source,bash]
----
mvn clean install
----

=== Running the application locally

To locally run the application, use the following command:

[source,bash]
----
mvn spring-boot:run
----

For local tests, a mockserver can be started with the provided docker-compose file.
It simulates a backend-service, that will be accessed by our application.

[source,bash]
----
docker-compose -f ./docker/docker-compose.yaml up
----

The mockserver can be reached via http://localhost:1080 and exposes a dashboard to monitor all requests is available via http://localhost:1080/mockserver/dashboard[Mockserver Dashboard].

This application exposes a gateway route that can be called with

[source,bash]
----
curl http://localhost:8080/question-route
----

This application exposes a REST endpoint that can be called with

[source,bash]
----
curl http://localhost:8080/question-controller
----
